In [1]:
import numpy as np

### arange()

In [2]:
array = np.arange(5)

In [3]:
array

array([0, 1, 2, 3, 4])

In [4]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10,2)

array([2, 4, 6, 8])

### zeros()

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones()

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace()

In [10]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

### eye()

In [11]:
np.eye(10) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### rand() y randn()

In [12]:
np. random.rand(5)

array([0.27857762, 0.10758463, 0.19795051, 0.33526558, 0.64762973])

In [13]:
np.random.rand(2,3)

array([[0.97424532, 0.49801126, 0.95125887],
       [0.41620723, 0.80009677, 0.4500532 ]])

In [14]:
np.random.randn(4)

array([ 1.22835575,  0.76384031, -0.874027  , -0.7013461 ])

In [15]:
np.random.randn(4,5)

array([[-1.59320704, -1.58868846, -0.09891883,  0.77112414,  1.1154529 ],
       [ 0.42286814,  0.50600284, -0.47023873,  1.13681123,  0.31235149],
       [-0.60503296, -0.39052366, -0.41239214,  0.28380292, -0.7647637 ],
       [-0.2731307 ,  1.07096198,  0.83932935, -0.01422726, -0.12786259]])

### Números aleatorios enteros, randint()

In [16]:
np.random.randint(1, 20)

18

In [17]:
np.random.randint(1, 20, 5)

array([ 2, 14,  3,  7, 15], dtype=int32)

### reshape()

In [18]:
array = np.random.randint(1, 100, 25)

In [19]:
array

array([52, 84, 17, 83, 21, 51, 83, 68,  8,  3, 57, 79, 17, 64, 29, 50, 40,
       26, 47, 77, 42, 50, 59, 27, 13], dtype=int32)

In [20]:
matriz = array.reshape(5,5)

In [21]:
matriz

array([[52, 84, 17, 83, 21],
       [51, 83, 68,  8,  3],
       [57, 79, 17, 64, 29],
       [50, 40, 26, 47, 77],
       [42, 50, 59, 27, 13]], dtype=int32)

In [22]:
array = np.random.randint(1,100,50)

In [23]:
array

array([66, 91, 87, 59, 93, 90, 55, 63, 28, 71, 37, 64, 70, 98, 55,  1, 55,
       47, 90,  5, 63, 10, 73, 72, 73, 86, 57, 83, 41, 83, 67, 56, 41, 90,
       81, 49, 81, 21, 25, 16, 57, 54, 21, 95, 25, 61, 55, 83, 82, 65],
      dtype=int32)

In [25]:
valor_maximo = array.max()
valor_maximo

np.int32(98)

In [26]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

np.int64(13)

In [27]:
valor_minimo = array.min()
valor_minimo

np.int32(1)

In [28]:
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

np.int64(15)

### Indexación en arrays

In [29]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
print(array[0])

0


In [32]:
print(array[2:4])

[2 3]


In [33]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Arrays de 2 dimensiones

In [35]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [36]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
array[0]

array([1, 2, 3])

In [39]:
array2 = array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
print(array[0,0])

1


In [43]:
array[:,0]

array([1, 4, 7])

In [44]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Seleccionar elementos de un array según una condición

In [45]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
condicion = array > 5

In [47]:
print(condicion)

[False False False False False False  True  True  True  True]


In [48]:
array[condicion]

array([6, 7, 8, 9])

In [49]:
array[array > 5]

array([6, 7, 8, 9])

In [50]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

### Operaciones con arrays

In [51]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [55]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [56]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [58]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [60]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [61]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [62]:
np.max(array)

np.int64(9)

In [63]:
np.min(array)

np.int64(0)