In [59]:
import numpy as np

### arange()

In [60]:
array = np.arange(5)

In [4]:
array

array([0, 1, 2, 3, 4])

In [5]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,10,2)

array([2, 4, 6, 8])

### zeros()

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones()

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace()

In [11]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

### eye()

In [12]:
np.eye(10) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### rand() y randn()

In [13]:
np. random.rand(5)

array([0.41603327, 0.85109741, 0.729862  , 0.61542597, 0.8001521 ])

In [14]:
np.random.rand(2,3)

array([[0.69574782, 0.92222773, 0.05663672],
       [0.60072194, 0.7888819 , 0.52897274]])

In [15]:
np.random.randn(4)

array([-1.64140418,  0.01388701, -0.70642496, -0.03646629])

In [16]:
np.random.randn(4,5)

array([[-0.17534903, -1.10432297, -1.32299815,  0.85039671,  0.55928294],
       [ 0.73289211, -0.20136189, -0.63192536, -0.40712482, -0.47176195],
       [-2.34407521,  0.99007172, -0.31614325, -0.41867393, -1.38067083],
       [ 0.73222093, -1.08636049,  0.09651945, -1.37621096, -1.47971143]])

### Números aleatorios enteros, randint()

In [17]:
np.random.randint(1, 20)

17

In [18]:
np.random.randint(1, 20, 5)

array([14, 11, 16,  3,  6], dtype=int32)

### reshape()

In [19]:
array = np.random.randint(1, 100, 25)

In [20]:
array

array([42, 38, 96, 86, 28, 16, 22, 39, 37, 14, 91, 75, 28, 70, 68, 27, 68,
       87, 64, 83, 70,  9, 97, 69, 51], dtype=int32)

In [21]:
matriz = array.reshape(5,5)

In [22]:
matriz

array([[42, 38, 96, 86, 28],
       [16, 22, 39, 37, 14],
       [91, 75, 28, 70, 68],
       [27, 68, 87, 64, 83],
       [70,  9, 97, 69, 51]], dtype=int32)

In [23]:
array = np.random.randint(1,100,50)

In [24]:
array

array([ 3, 17, 37, 22, 66, 13, 33, 51,  4,  6, 33, 25, 49, 86, 63, 49, 60,
       93, 62, 83, 12, 12,  4, 80, 64, 14, 45, 40, 18, 14, 42, 34, 93, 56,
       31, 54, 22, 68, 82, 63,  6,  9, 63, 12, 63, 67, 76, 56,  4, 72],
      dtype=int32)

In [25]:
valor_maximo = array.max()
valor_maximo

np.int32(93)

In [26]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

np.int64(17)

In [27]:
valor_minimo = array.min()
valor_minimo

np.int32(3)

In [28]:
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

np.int64(0)

### Indexación en arrays

In [29]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
print(array[0])

0


In [31]:
print(array[2:4])

[2 3]


In [32]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Arrays de 2 dimensiones

In [33]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [34]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array[0]

array([1, 2, 3])

In [36]:
array2 = array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(array[0,0])

1


In [38]:
array[:,0]

array([1, 4, 7])

In [39]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Seleccionar elementos de un array según una condición

In [40]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
condicion = array > 5

In [42]:
print(condicion)

[False False False False False False  True  True  True  True]


In [43]:
array[condicion]

array([6, 7, 8, 9])

In [44]:
array[array > 5]

array([6, 7, 8, 9])

In [45]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

### Operaciones con arrays

In [46]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [50]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [52]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [54]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [55]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [56]:
np.max(array)

np.int64(9)

In [57]:
np.min(array)

np.int64(0)